### ISSUE TITLE
DWI in BIDS

### ISSUE THREAD

**Issue by gsudre** [ABCD-STUDY/nda-abcd-collection-3165#15]
Hello,

I have a question about DWI data and their conversion to BIDS format. I looked at a random sample of 1000 subjects in the release, but 300 of them didn't have DWI data in their BIDS directory. Most of those subjects have DTI data in tabular format. EDIT: (Apologies but we cannot post subject IDs --edited by @ericfeczko ). What were the criteria used to select which subjects had their Dicoms converted to BIDS?

Thanks a bunch!

Gustavo

**Comment by arueter1** [comment]
Hi Gustavo, thanks for your question. We'll get back to you about this as soon as we are able.

**Comment by ericfeczko** [comment]
Hi Gustavo!

My apologies for the delayed reply. Just as a reminder, subject IDs cannot be posted on github issues according to the NDA. Please feel free to contact us via email with specific examples (feczk001@umn.edu).

Subjects were identified and DWI data was converted based on the fast-track QC available at the time of processing (depends on the release date). See here ( https://collection3165.readthedocs.io/en/stable/release_notes/#2-background ) to see the latest version of the fast-track QC used.  Because the fast-track QC is updated both bi-annually and when serious errors are noted, it is certainly possible for data available via DEAP (i.e. the tabulated data) to be unconverted as a result. The NDA is currently reviewing our latest edits to the ABCC, which includes subjects that were missing data in our prior release due to this issue. We expect that data to be available by the end of August.

Feel free to contact us with an email containing the list of subjects (apologies again for the ID restrictions) and we can follow-up further there if you'd like.

-Eric
