### ISSUE TITLE
Why are you all so awesome?

### ISSUE THREAD

**Issue by katemills** [ABCD-STUDY/nda-abcd-collection-3165#16]
Greeting from the MDC ABCD workshop

**Comment by ericearl** [comment]
@katemills 

I'm awesome because I make time for issues like these.  I feel @ericfeczko is awesome because he truly and fully answers issues like these.  @perronea is awesome because he can solve literally any programming task.  And @arueter1 is awesome because she keeps us all on track despite our schedules.

But maybe that's all opinion...

**Comment by arueter1** [comment]
Nice to meet you Kate! :)
