### ISSUE TITLE
Bug in script to create desc-includingFD_motion.tsv.

### ISSUE THREAD

**Issue by arueter1** [ABCD-STUDY/nda-abcd-collection-3165#20]
Need to add an update to the ReadTheDocs along the lines of: "the file desc-includingFD_motion.tsv was produced for X reason. It is no longer going to be supported. For future reference, it is found [path]." It may also be good to mention that we had to do this because we only had the derivatives available in the past for one particular project.

**Comment by ericfeczko** [comment]
Added this:

The file desc-includingFD_motion.tsv was produced post-processing as an interface for loading frame-by-frame motion numbers (e.g. X,Y,Z, roll, pitch, and yaw) as tab separated values. It is no longer going to be supported since this is not part of the standard processing stream. For future reference, it is found in the "func" derivatives folder, as described above.

Closing the ticket, feel free to reopen if edits are needed :)
