### ISSUE TITLE
Why are there only 6701 dMRI data for the subject in the NDA Collection 3165 DCAN Labs ABCD-BIDS (ABCC dataset)

### ISSUE THREAD

**Issue by zhangjb35** [ABCD-STUDY/nda-abcd-collection-3165#27]
Hi, 
I accessed the ABCC collection (Collection 3165) on NDA, and download the dMRI dataset with the method introduced at
[https://github.com/ABCD-STUDY/nda-abcd-collection-3165 3](https://github.com/ABCD-STUDY/nda-abcd-collection-3165), but I only downloaded dMRI data of 6701 subjects. I also check the datastructure_manifest.txt access via NDA. There are only 6701 subject keys in that text file.

Why there is only 6701 subject for dMRI data? Based the fastqc.txt, I get 9709 subject pass the qc. (fastqc.ftq_complete == 1) & (fastqc.ftq_quality==1) & (fastqc.ftq_usable==1)

**Comment by audreymhoughton** [comment]
Hi @Jinboasltw - we believe this happened due to an older fast track being used to convert the BIDS data originally, and we have not gone back through to update the BIDS conversion for DWI since that first upload. This will be added to our to-do list. 

I am going to close this issue, but keep an eye out on the [ABCC readthedocs Release Notes](https://collection3165.readthedocs.io/en/stable/release_notes/) for when we get a chance to upload/convert new ABCC DWI inputs. Thank you for pointing this out!
