### ISSUE TITLE
Fieldmap's "IntendedFor" field

### ISSUE THREAD

**Issue by ericearl** [ABCD-STUDY/nda-abcd-collection-3165#4]
Migrated from old repo:

I am curious how many field maps have empty IntendedFor list fields in their JSONs. I don't think we intended that IntendedFor behavior so I am leaving this issue open for that reason until we can be certain why there are any empty IntendedFor fields in field map data anywhere. I think it's fine in BIDS to omit an IntendedFor field in a field map if it's not intended for use.

**Comment by gsudre** [comment]
I wanted to follow up on this. I noticed several baseline scans with empty IntendedFor fields in Diffusion FMAPs in one direction but not the other. For example, sub-*ses-baselineYear1Arm1_acq-dwi_dir-AP_epi.json has the field as ["ses-baselineYear1Arm1/dwi/sub-*_ses-baselineYear1Arm1_dwi.nii.gz"], but sub-*ses-baselineYear1Arm1_acq-dwi_dir-PA_epi.json is []. Was that intentional? Or should we go ahead and fill in the DWI session in the tags for both field maps (assuming they are both of acceptable quality)?

**Comment by perronea** [comment]
This actually was _Intended_... AP is the reverse phase encoding of the DWI, but PA is the forward phase encoding, which can be replaced with the first volume of the DWI itself. If we require both AP and PA then to maintain consistency we would have to throw out some subjects with a bad PA fieldmap. We decided to simply replace the PA fieldmap with the first volume of the DWI.
