### ISSUE TITLE
Missing parcellation

### ISSUE THREAD

**Issue by bkossows** [ABCD-STUDY/nda-abcd-collection-3165#48]
I would like to extract averaged myelin values from the aparc and apar2009s parcellation. I've found dscalar.nii files in the repository, but there are no dlabel.nii files for the respective parcellation. I am not sure, but it seems like the individual parcellations are required to run the following command. Am I correct?
`wb_command -cifti-parcellate xxx.dscalar.nii xxx.aparc.a2009s.32k_fs_LR.dlabel.nii COLUMN output.pscalar.nii`

**Comment by ericfeczko** [comment]
I think there's some epistemological confusion here. Please allow me to clarify:

subject-specific label files are typically annotations that leverage the subject's measured data in order to customize the parcellation scheme -- also known as **precision functional mapping** this leads to different ROIs and differently shaped systems from subject to subject. Examples can be found here:

https://doi.org/10.1101/2022.01.12.475422 

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5568802/

https://www.cell.com/neuron/pdf/S0896-6273(17)30613-X.pdf

In general, template label files that are applied consistently across multiple subjects are often derived _a priori_ from independent data averaged across many subjects (not a literal average, of course). These label files are the same for each subject, and enable comparisons of the same ROI across mutliple subject -- at the cost of precision. These aren't actually specifically labeled for each subject, but in some pipelines, may be provided as a convenience.

As long as such label files are properly mapped to the same standard space (for ABCC data, this would be the MNI 2006 Nonlinear asymmetric atlas in volume, and freesurfer L/R 164/32k for the surface), the cifti parcellate command you have above should work just fine.

I'm curious why Rahul Desikan's (זכרונו לברכה) atlas? 

We do have a collection of general ROI sets that can be used for this purpose, here's a link to a folder containing them:

https://drive.google.com/drive/folders/1XUNzIGblYroDvqcNb-GAXNRAfGlZGjek?usp=share_link


Finally, I would be cautious about using myelin maps in general and do some EDA on the stability first. Some normalization transforms to the data may be warranted.

**Comment by bkossows** [comment]
Thank you for the prompt response. I appreciate the atlases you sent me to obtain the relevant statistics. However, I still have reservations about the redundancy of the DK parcellation for the specific participants. When I examined the output of the [HCP-ABCD pipeline](https://github.com/DCAN-Labs/nhp-abcd-bids-pipeline), I noticed a significant difference between "fsaverage" and the individual parcellation (for fsLR32k). I did not enable MPM registration for my data. Do you think that may have been the cause?
I would like to use the ABCD myelin data as a reference for my dataset. Could you please confirm if the file "sub-#/ses-#/anat/sub-#_ses-#_space-fsLR32k_myelinmap.dscalar.nii" corresponds to "#.MyelinMap.32k_fs_LR.dscalar.nii" or the bias-corrected "#.MyelinMap_BC.32k_fs_LR.dscalar.nii" from the HCP ABCD pipeline?
With kind regards,

**Comment by ericfeczko** [comment]
The above link takes me to the NHP version of our pipeline -- we also have[ human child/adult](https://github.com/DCAN-Labs/abcd-hcp-pipeline) and [human infant ](https://github.com/DCAN-Labs/dcan-infant-pipeline). Given the repository, I was under the impression that the child/adult pipeline was being used -- is that correct or am I mistaken? 

No worries either way, just want to make sure we're on the same page :) 

Ok, I think I understand now -- you wanted to use the freesurfer naive bayes classified parcellations based on Rahul's manually drawn labels. We don't routinely pull these through to the derivatives -- though they are present in the processed output itself (prior to running file-mapper above). 

The "fsaverage" will indeed be different from "fsLR32k". The fsaverage refers to freesurfer's fsaverage template as opposed to the freesurfer L/R resampled to 32k vertices. 

Yes the correspondence should be the same to the 32k_fs_LR.dscalar.nii -- we have a list of all the correspondences [here](https://github.com/DCAN-Labs/file-mapper/blob/master/examples/abcd-filemapper.json), if you're interested :)

**Comment by bkossows** [comment]
Thank you again for the clarification. We used [human child/adult](https://github.com/DCAN-Labs/abcd-hcp-pipeline). So, you're saying that the pipeline we ran is not the same one used for the NDA ABCD Collection?

**Comment by ericfeczko** [comment]
the NDA ABCD collection used the [human child/adult](https://github.com/DCAN-Labs/abcd-hcp-pipeline). If you're running the pipeline yourself, one can pull this in assuming one has not run the customclean stage. 

Happy to walk this through in a quick zoom meeting if you'd like -- feel free to contact me at feczk001@umn.edu

**Comment by MarcinSzyWy** [comment]
Eric, thanks a lot for these clarifications!
