### ISSUE TITLE
Question about missing subjects in the task e-prime data

### ISSUE THREAD

**Issue by Jihyuncindyhur** [ABCD-STUDY/nda-abcd-collection-3165#5]
Hi! I recently downloaded fMRI e-prime data (sourcedata.func.task_events) with the nda-abcd-s3-downloader from DCAN lab. Thanks so much for providing such a great tool!!

I had a question about the e-prime data. The total number of subjects available for downloading was only 8135, but I found no exclusion criteria in the `fmriresults01 data`. Could someone tell me the exclusion criteria for the e-prime data? Thanks!

**Comment by ericearl** [comment]
@Jihyuncindyhur Sorry for the very long wait.  I think you may have gotten an answer to this since then, but just so it's out here:

I don't believe there were any excluded task-based (non-resting-state) fMRI E-Prime files for subjects within our Collection 3165 repository.  I wonder if you're referring to subjects who were not in our repository, but had E-Prime files?  You can see the full participant list details here:

https://collection3165.readthedocs.io/en/stable/recommendations/#2-the-bids-participants-files-and-matched-groups

**Comment by ericearl** [comment]
Closing unless @Jihyuncindyhur comes back with another comment.
