### ISSUE TITLE
Collection 3165 functional connecitivity derivatives

### ISSUE THREAD

**Issue by pkashya** [ABCD-STUDY/nda-abcd-collection-3165#52]
Hi,

I'm trying to access the functional connectivity derivatives for the ABCD study. After downloading the data from the NDA download manager it looks like there are only about 150 subjects whose BOLD data is preprocessed each for Power2011, Yeo2011 and HCP2016 templates. Maybe I'm missing something or are the outputs are stored elsewhere other than fmriresults01/derivatives/abcd-hcp-pipeline/?

Please let me know,

**Comment by ericfeczko** [comment]
Hey @pkashya 


My apologies for the late reply. We typically recommend that folks use our nda downloader instead of the NDA download manager, due to the size of the repository. 

Documentation regarding best ways to access the data can be found on our readthdocs https://collection3165.readthedocs.io/en/stable/recommendations/#4-downloading-and-unpacking-data documentation on the downloader itself can be found on its github page: https://github.com/ABCD-STUDY/nda-abcd-s3-downloader

Hope this helps!
