### ISSUE TITLE
Clarification about pconn files

### ISSUE THREAD

**Issue by audreymhoughton** [ABCD-STUDY/nda-abcd-collection-3165#55]
Transferring @traceyshi 's issue from the DCAN Labs repo.

Hi,

Two related questions -

(1) For the connectivity matrices/frame censors with 5- and 10-minutes of below-threshold motion (https://collection3165.readthedocs.io/en/stable/derivatives/#parcellated-connectivity-derivativesfuncpconns), how are the timepoints to include selected? I.e., if the participant has >10 minutes of low-motion data, how are only 10 minutes worth of frames selected for that pconn?

(2) When I use the nda-abcd-s3-downloader, I don't get any pconn files for the participants assigned to Group 3 of the matched groups (https://collection3165.readthedocs.io/en/stable/recommendations/#2-the-bids-participants-files-and-matched-groups). I can download ptseries for many of these participants, so they're not entirely missing or excluded. Is the lack of pconns intentional? The first question above is so I can reproduce the pconn files for Group 3, so if they are available elsewhere that would also solve my problem.

Thanks in advance.

**Comment by ericearl** [comment]
@traceyshi

For question 1: Let's say the participant has 11 minutes of good data. If I recall correctly the code takes 1 minute uniform-randomly sampled out without replacement. Is this right @ericfeczko? (it's been a while for me...)

For question 2: I don't know, but maybe @hough129 can see if those files even exist outside of the NDA. My suspicion is maybe not since the analyses of PCONN data were done on ARMS groups 1 and 2.

**Comment by ericfeczko** [comment]
@ericearl is correct, ARMS group 3 was kept independent for other purposes, and data were randomly selected at 1 minute segments.
