### ISSUE TITLE
fMRIPrep 23.0.0rc1

### ISSUE THREAD

**Issue by dmoracze** [ABCD-STUDY/nda-abcd-collection-3165#58]
Hello - I see on the 'Coming Soon' section:
New version of [fMRIPrep](https://fmriprep.org/) 23.0.0rc1 year 1 derivatives.

Is someone actively working on this? It would be helpful to have an area to examine planned derivatives, a point person, and estimated date of upload. This way we do not duplicate our efforts.

**Comment by LuciMoore** [comment]
Hi, @dmoracze. Apologies for the late reply. We are gearing up for a new release shortly, but I don't believe we plan to include the fMRIPrep outputs until a later release. However, it's my understanding that Michael Demidenko (@demidenm on GitHub) is actively working on this. I've invited him as a collaborator to this repo so that you two can connect and I can tag him, but in the meantime I'll share the issue with him directly

**Comment by demidenm** [comment]
@dmoracze - I have previously ran ABCC Baseline and Year1 data (approx 17000 subjects total) through MRIQC v23.1.0 and fMRIPrep v23.1.4 for a couple of my projects (note, 23.0.0rc1 had some lingering issues that are resolved in subsequent release). Since that time, the ABCC data had some configuration updates to fix lingering items. This updated some of the BIDS input files. Unfortunately, I am unable easily compare which were updated and the extent to the revisions. Thus, to ensure consistency, in September I am planning to resubmit batch jobs using the more recent version of fMRIPrep, like v24.0.0,  and MRIQC v23.1.0 (since not including DWI in my workflow not doing 24.0.0). I already have the code in place to resubmit batch jobs, logging errors as it goes. So booting it up and running it will just take time. MRIQC would take ~1-2 weeks. fMRIPrep longer, around ~3-5 weeks. 

Below are the singularity runs I have been using.

**MRIQC:**
```
singularity run --cleanenv \
-B ${data_dir}/bids_dir/sub-${subj_id}_ses-${ses_id}:/bids_dir \
-B ${data_dir}/processed/sub-${subj_id}_ses-${ses_id}:/output_dir \
-B ${data_dir}/work_dir//sub-${subj_id}_ses-${ses_id}:/wd \
${sif_img} \
/bids_dir /output_dir participant \
--ants-nthreads 8 \
--nprocs 12 \
--mem_gb 30 \
-vv \
--verbose-reports \
-w /wd \
-m bold T1w T2w
```

**fMRIPrep:**
```
singularity run --cleanenv \
-B ${data_dir}/bids_dir/sub-${subj_id}_ses-${ses_id}:/bids_dir \
-B ${data_dir}/processed/${fmriprep_ver}/sub-${subj_id}_ses-${ses_id}:/output_dir \
-B ${data_dir}/work_dir/${fmriprep_ver}/sub-${subj_id}_ses-${ses_id}:/wd \
-B ${FS_L}:/freesurf_license.txt \
-B ${run_dir}/task_list.json:/task_list.json \
${sif_img} \
/bids_dir /output_dir participant \
--participant-label ${subj_id} \
--fs-license-file /freesurf_license.txt \
--bids-filter-file /task_list.json \ <-- MID, SST, nback, rest
--ignore slicetiming \
--fd-spike-threshold .9 \
--output-space MNI152NLin2009cAsym:res-2 \
--project-goodvoxels \
--cifti-output 91k \
-vv \
-w /wd
```

There are some checks that I am working in after preprocessing to add additional information with the derivatives that can be used with DAIRC flags. One is to flag the [aCompcor ROI mask error](https://github.com/nipreps/fmriprep/issues/3195) in fMRIPrep. A couple others are to track the type of fieldmap correction is applied and the overlap between brain masks and BOLD masks. The latter is to flag potential failures in FS and SDC. Happy to get thoughts or create a repo where you can add recommendations, etc.
