### ISSUE TITLE
Question about "matched_group" field in the participants file

### ISSUE THREAD

**Issue by ebridge2** [ABCD-STUDY/nda-abcd-collection-3165#71]
Hi all, first off, I wanted to thank the authors of this effort for doing such a comprehensive and holistic organization of the data from the ABCD study. I had a quick question: I am looking at the `participants.tsv` file from the download, `participants_v1.0.3.zip` found [here](https://nda.nih.gov/edit_collection.html?id=3165). 

I see some documentation [on the ABCC 3165 documentation page](https://collection3165.readthedocs.io/en/stable/recommendations/) which suggests that "the `matched_group` field is the product of comparisons across site, age, sex, ethnicity, grade, highest level of parental education, handedness, combined family income, exposure to anesthesia, and family-relatedness which show no significant differences between the ABCD-1 and ABCD-2 groups". Are there more specifics as to how, exactly, this matching was determined? I cannot find any links within the documentation, nor the ABCD downloads through NDA, but perhaps I'm just not looking in the right places as there is a lot of stuff to sort through. 

Thanks in advance for any help you can provide.

**Comment by LuciMoore** [comment]
@ebridge2 thank you for your question. we are in the process of overhauling and updating the documentation in preparation for release 6.0 coming this fall. We have documentation written up for this and just haven't integrated it yet. I added the draft as an issue [here](https://github.com/DCAN-Labs/automated-subset-analysis/issues/2) in the meantime.

Feel free to close this issue if the information provided is sufficient or follow up with more questions (since it's just a draft I imagine there are some points that are unclear)

**Comment by ebridge2** [comment]
Hi @LuciMoore; I think the information despite being a draft suffices in conjunction with the code I found in the corresponding repo which clarified more technical aspects. Thanks very much!
