### ISSUE TITLE
Documentation suggestions

### ISSUE THREAD

**Issue by mharms** [ABCD-STUDY/nda-abcd-collection-3165#9]
It would be a nice addition if the documentation specified whether or not there is a mechanism for updating ("patching") to the latest release (e.g, as part of the "Release Notes", or a standalone "Downloading" section).

Also, the instructions/process for downloading the data is a bit buried in the middle of the "Recommendations" section (which is not the section where I was expecting to find that key information).  It would be helpful for users if the instructions for Downloading and Unpacking Data were more prominent, perhaps as their own "main" section directly under the Table of Contents. (e.g., as a stand-alone "Downloading" section right after the "Release Notes" section).

**Comment by mharms** [comment]
Relatedly, how does one know exactly which release version they have from the downloaded files?  I just downloaded the data for 1 subject as a test. The resulting `README` and `dataset_description.json` don't indicate a specific data release version. And the `CHANGES` file indicates that what I actually got is version "0.0.0":
```
0.0.0 2018-08-22
  - Initial collection.
```

**Comment by ericearl** [comment]
@mharms Thank you for this GitHub issue, I really appreciate the thought you put into it.

Your first comment looked like it was mostly suggestions, but the second comment about knowing what version of things people are getting is very valid.

When we were trying to conform to BIDS standards and release the first wave of data with the NDA we did some extra uploading of those BIDS dataset parent folder modality-agnostic files (README, CHANGES, dataset_description.json).  However, you're right we haven't updated those since release so when a data-user like you downloads that data they'll always receive the same OLD changes and readme files.  What we should have done in retrospect is just uploaded the BIDS modality-agnostic files  as a downloadable ZIP or TAR file to be unpacked into the top-level of your downloaded data.  This should be made clear in our readthedocs site.

I will expand on all this in the next documentation update.  Did I miss anything of what you were asking here?

**Comment by mharms** [comment]
@ericearl Not quite sure what you are proposing, but it seems somewhat pointless for the Documentation to refer to different data "versions" if there is no easy way to distinguish which particular version you have from the actual downloaded files.

**Comment by mharms** [comment]
Couldn't you have updated the "modality-agnostic" files as part of the same uploads to the NDA in which you added other files?

**Comment by ericearl** [comment]
@mharms In this data set, we upload "manifests" to the NDA which are effectively small sets of data grouped into a single NDA record in their database.  It's like having files, folders, sub-files, and sub-folders all associated with one record so when a user goes to download that little record, they get that group of files.

So what happened was I wanted users to be able to have the modality-agnostic files no matter what they downloaded and in retrospect I don't think that was a good choice since updating or changing a record in the NDA database is non-trivial.

I think what I will do in future releases is update the modality-agnostic files and upload them as a ZIP file that can be downloaded for each release with any relevant changes documented in the README, CHANGES, and dataset_description.json files inside.  I will try to get this released in the next two weeks along with a "Version" section update to the readthedocs and I will message back here afterward.

Again, thanks for your attention to detail and good suggestions.

**Comment by mharms** [comment]
Yes, this highlights one of the problems with the NDA not having a mechanism for updating a previous upload.  So, the different data "releases" have been solely about adding new files (via newly uploaded manifests), as opposed to changing any existing files?

**Comment by mharms** [comment]
I guess we have no control over the order in which manifests are "unpacked" during a download, right?  Otherwise, you could change the modality-agnostic files by including those particular files again as part of the manifests that added the new files, and then relying on the order of unpacking to ensure that the desired one got unpacked last.

**Comment by ericfeczko** [comment]
@mharms We're working on a potential solution to this problem, where the data will be "versioned" in a standardized way, to ensure that people can match against prior downloads. We're still in the process of implementing and testing, but will report back when it's ready.

Apologies for the data. As you know, so many things to do, and so little time :)

Happy to chat more about our potential solution in person, if you'd like.
